import Head from "next/head";
import React from "react";
import Link from "next/link";

const Layout: React.FC = ({ children }) => {
  const [cookie, setCookie] = React.useState<any>(false);
  console.log(cookie);
  React.useEffect(() => {
    async function fetchApi() {
      let response = await fetch("/api/cookie");
      response = await response.json().then((data) => data.cookie.appSession);
      console.log(response);
      setCookie(response);
    }
    fetchApi();
  }, []);

  return (
    <>
      <Head>
        <title>Catalog Games</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin="anonymous"
        />
      </Head>

      <div className="pos-f-t">
        <div className="collapse" id="navbarToggleExternalContent">
          <div className="bg-dark p-4">
            <h4 className="text-white">Collapsed content</h4>
            <span className="text-muted">Toggleable via the navbar brand.</span>
          </div>
        </div>
        <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
          <div className="container-fluid">
            <Link href="/">
              <a className="navbar-brand user-select-none">Home</a>
            </Link>

            <button
              className="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarSupportedContent"
              aria-controls="nnavbarToggleExternalContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span className="navbar-toggler-icon"></span>
            </button>

            <div
              className="collapse navbar-collapse"
              id="navbarSupportedContent"
            >
              <ul className="navbar-nav mr-auto">
                <li className="nav-item active">
                  <Link href="/games">
                    <a className="nav-link user-select-none">Games</a>
                  </Link>
                </li>
                <li className="nav-item active">
                  <Link href="/platforms">
                    <a className="nav-link user-select-none">Platforms</a>
                  </Link>
                </li>
                <li className="nav-item active">
                  <Link href="/genres">
                    <a className="nav-link user-select-none">Genres</a>
                  </Link>
                </li>
              </ul>
            </div>
            <form className="zform-inline" action="POST">
              <input
                className="form-control mr-sm-2"
                type="search"
                placeholder="Search"
                aria-label="Search"
              />
            </form>

            <form className="zform-inline" action="/api/auth/login"></form>

            {!cookie ? (
              <button
                className="btn btn-outline-success my-2 my-sm-0"
                type="submit"
              >
                <a href="/api/auth/login">Login</a>
              </button>
            ) : (
              <button
                className="btn btn-outline-success my-2 my-sm-0"
                type="submit"
              >
                <a href="/api/auth/logout">Logout</a>
              </button>
            )}

            {!cookie ? (
              <></>
            ) : (
              <button
                className="btn btn-outline-success my-2 my-sm-0"
                type="submit"
              >
                <a href="/account">Mon Compte</a>
              </button>
            )}
          </div>
        </nav>
        {children}
      </div>
    </>
  );
};
export default Layout;
